# Generated by Django 4.1.4 on 2022-12-17 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_alter_todolist_icon_color'),
        ('todoitems', '0002_alter_todoitem_todolist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='todolist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='todolist.todolist'),
            preserve_default=False,
        ),
    ]
