# Generated by Django 4.1.4 on 2022-12-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon_color', models.CharField(blank=True, max_length=255, null=True, verbose_name='icon color')),
            ],
        ),
    ]
