# Generated by Django 4.1.4 on 2022-12-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='icon_color',
            field=models.CharField(blank=True, default='#d848d6', max_length=255, null=True, verbose_name='icon color'),
        ),
    ]
