# Generated by Django 4.1.4 on 2022-12-20 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_todolist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='user',
        ),
    ]
